"""Port of Modules/watcher_workspace.ps1 - bead mcpw-xeu.2.

Workspace identity for the watcher launcher (beads mcpw-ybs.2).

The launcher is meant to be started from ANY repository through a shortcut, so
every MACHINE-GLOBAL resource it owns must be keyed by the CALLER's repository:
  - the teardown state file      (Stop-AllWatchers must read ITS OWN roots)
  - the pane + log scratch dirs  (each workspace owns its pane tailers)
  - the launcher lock + mutexes  (FIRST-WINS per workspace, see mcpw-ybs.4)
  - the startup orphan sweep     (never kill a sibling repository's watchers)

ONE canonical derivation lives here. A disagreement about a key between the
launcher, the teardown module and the tests would SILENTLY disable a safety gate,
so this file is the single source of truth. Do not re-implement it.

SAFE TO IMPORT: no top-level side effects.

TWO REPRESENTATIONS EXIST UNTIL THE LAUNCHER IS PORTED. The PowerShell module is
still live. tests/test_ported_leaf_modules.py pins the key derivation against
vectors generated by running the .ps1, so the two cannot drift silently.

Fidelity notes, verified against the live .ps1 on 2026-09-23:
  - Get-WatchersWorkspaceKey('J:\\audio\\MCP-Watchers')  -> ad90e3fb
  - Get-WatchersWorkspaceKey('J:\\audio\\VAD')           -> 77442b14
    Both match the keys recorded in the mcpw-ybs close reason.
  - ToLowerInvariant() is reproduced with str.lower(). For ASCII paths the two
    agree, which is every path pinned in the tests. They could differ on exotic
    Unicode case mappings; if a non-ASCII workspace root ever matters, generate a
    vector from the .ps1 first rather than trusting this note.
"""
import hashlib
import os

# A workspace root shorter than this is ignored by the attribution test: a drive
# root such as C:\\ would otherwise attribute every process on the machine.
_MIN_ATTRIBUTABLE_ROOT = 4


def get_watchers_workspace_key(path=None):
    """Derive a stable 8-character lowercase hex key for a workspace path.

    The path is normalised (absolute, lowercased, no trailing separator) and
    hashed with SHA-256. Eight hex characters give about 4.3e9 values, which is
    ample for the handful of repositories on one machine. The short form matters
    because the key is embedded in Windows Terminal command lines and in Windows
    named-mutex names.
    """
    if not path:
        path = os.getcwd()
    if not path:
        return "default"

    normalized = path.rstrip("\\/").lower()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:8]


def get_watchers_workspace_root(path=None, env=None, cwd=None):
    """Return the workspace root a launcher was INVOKED from.

    Resolution order:
      1. the explicit path argument
      2. VAD_WATCHERS_WORKSPACE_ROOT, which the launcher exports to its children
         and which a caller can set to make a path explicit
      3. the current location

    Never returns the launcher's own script folder. That folder is $scriptDir and
    is a SEPARATE concept: it locates the Modules\\watcher_*.ps1 siblings and must
    never become the watched workspace.
    """
    if path:
        return path.rstrip("\\/")

    environ = os.environ if env is None else env
    from_env = environ.get("VAD_WATCHERS_WORKSPACE_ROOT")
    if from_env:
        return from_env.rstrip("\\/")

    location = cwd if cwd is not None else os.getcwd()
    if not location:
        return ""
    return location.rstrip("\\/")


def test_watchers_process_attribution(command_line, workspace_key, workspace_root):
    """Decide whether a candidate process belongs to THIS workspace.

    Used by the launcher's startup orphan sweep, which is a FALLBACK for orphans
    the PID-scoped Stop-AllWatchers could not reach. The sweep must FAIL SAFE:
    skipping an unattributable process can leave an orphan, which is harmless,
    whereas terminating it can kill a sibling repository's LIVE watcher.

    Attribution is by COMMAND LINE only, because Win32_Process exposes no working
    directory. A process whose command line carries no workspace marker therefore
    cannot be attributed, and is never terminated.

    Two markers are accepted:
      1. the 8-character workspace key. The keyed pane dir and log dir put it on
         the command line of everything the launcher spawns with a path.
      2. the absolute workspace root. Catches a process started with the
         workspace as an explicit argument.

    Comparison is ordinal-ignore-case, reproduced here with str.lower(); the
    ASCII cases pinned in the tests agree with the .ps1 exactly.
    """
    if not command_line:
        return False

    if workspace_key and workspace_key.lower() in command_line.lower():
        return True

    if workspace_root and len(workspace_root) >= _MIN_ATTRIBUTABLE_ROOT:
        if workspace_root.lower() in command_line.lower():
            return True

    return False
