"""Acceptance suite for the first ported leaf modules - bead mcpw-xeu.2.

The Python modules under Modules\\*.py are ports of live PowerShell modules. The
PowerShell originals are STILL the ones the launcher and the generated pane
scripts use, so for now each piece of logic has two representations. This suite
therefore does two separate jobs:

  1. BEHAVIOUR - exercises the Python modules directly, by importing them. This
     is the point of porting: the PowerShell suites for the same logic have to
     slice source text out of a .ps1 by string anchor and Invoke-Expression it
     (38 Get-Content -Raw and 31 Invoke-Expression across tests\\). That technique
     breaks silently when an anchor drifts - see mcpw-d76 for one found in the
     wild. A real import cannot drift.

  2. EQUIVALENCE - pins the Python modules against vectors generated by RUNNING
     the .ps1 on 2026-09-23, and re-parses the sweep table out of
     watcher_patterns.ps1 on every run. Without this, porting a safety-critical
     table and an attribution gate would create a silent drift path: the sweep
     would keep "working" while matching the wrong processes.

The pinned vectors are real outputs, not hand-written expectations. Regenerate
them by dot-sourcing Modules\\watcher_workspace.ps1 and Modules\\watcher_patterns.ps1
and calling the functions - do not edit a vector to make a test pass.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Modules import watcher_log_tail, watcher_patterns, watcher_workspace  # noqa: E402

PATTERNS_PS1 = ROOT / "Modules" / "watcher_patterns.ps1"
WORKSPACE_PS1 = ROOT / "Modules" / "watcher_workspace.ps1"
LOG_TAIL_PS1 = ROOT / "Modules" / "watcher_log_tail.ps1"

# ---------------------------------------------------------------------------
# 2. Equivalence: the sweep table
# ---------------------------------------------------------------------------

_ENTRY = re.compile(
    r"@\{\s*Name\s*=\s*'([^']*)'\s*;\s*Pattern\s*=\s*'([^']*)'\s*"
    r"(?:[;,]\s*Persistent\s*=\s*(\$true))?\s*\}"
)


def _ps1_sweep_table():
    src = PATTERNS_PS1.read_text(encoding="utf-8")
    entries = _ENTRY.findall(src)
    assert entries, "parsed no sweep entries out of watcher_patterns.ps1"
    return [(name, pattern, persistent == "$true") for name, pattern, persistent in entries]


def test_sweep_table_matches_ps1_exactly():
    """The ported table must equal the .ps1 table: same entries, same order."""
    assert _ps1_sweep_table() == [
        (entry.name, entry.pattern, entry.persistent)
        for entry in watcher_patterns.WATCHER_SWEEP_PATTERNS
    ], (
        "Modules/watcher_patterns.py and Modules/watcher_patterns.ps1 disagree. "
        "The sweep table is the single source of truth for teardown; fix the "
        "divergence before either side is used."
    )


def test_persistent_flags_are_carried():
    """`Persistent = $true` marks singletons that must never be swept on takeover."""
    persistent = {
        entry.name for entry in watcher_patterns.WATCHER_SWEEP_PATTERNS if entry.persistent
    }
    # claude-mcp.exe, node.exe claude-mcp-server, python.exe mcp_agent_mail,
    # python.exe embed_server. The mail and embed singletons are shared with
    # sibling checkouts - see mcpw-xeu.9.
    assert len([e for e in watcher_patterns.WATCHER_SWEEP_PATTERNS if e.persistent]) == 4
    assert "python.exe" in persistent


# ---------------------------------------------------------------------------
# 2. Equivalence: sweep matching
# ---------------------------------------------------------------------------

# (command_line, pattern, expected) - expected generated by running
# Test-WatcherSweepMatch in the live .ps1.
SWEEP_MATCH_VECTORS = [
    ("cmd --repo j:\\audio\\vad", "watch", False),
    ("node.exe codegraph watch C:\\x", "codegraph watch", True),
    # the codegraph MCP backend must NOT be swept by the watch pattern
    ("node.exe cli.js mcp --multi-repo", "codegraph watch", False),
    ("node.exe codegraph\\dist\\cli.js watch C:\\x", "codegraph\\dist\\cli.js watch", True),
    ("anything", "", True),
    ("", "", False),
    # heimdall reconciler vs the heimdall MCP backend
    ("node.exe C:\\x\\heimdall.js daemon", "heimdall.js daemon", True),
    ("node.exe C:\\x\\heimdall.js mcp", "heimdall.js daemon", False),
    # PowerShell -match is case-insensitive; this vector is what proves the port
    # reproduces that rather than doing a case-sensitive compare.
    (
        "PS -File C:\\TEMP\\VAD-WATCHERS\\77442B14\\PANES\\TAIL_GREPAI.PS1",
        "panes\\tail_",
        True,
    ),
]


def test_sweep_match_matches_ps1_vectors():
    for command_line, pattern, expected in SWEEP_MATCH_VECTORS:
        actual = watcher_patterns.test_watcher_sweep_match(command_line, pattern)
        assert actual is expected, (
            f"test_watcher_sweep_match({command_line!r}, {pattern!r}) "
            f"returned {actual}, .ps1 returned {expected}"
        )


def test_empty_pattern_is_match_all_but_never_an_empty_command_line():
    match_all = [e for e in watcher_patterns.WATCHER_SWEEP_PATTERNS if e.pattern == ""]
    assert match_all, "expected match-all entries (graphify-rs rebuild children)"
    assert watcher_patterns.test_watcher_sweep_match("anything", "") is True
    assert watcher_patterns.test_watcher_sweep_match("", "") is False
    assert watcher_patterns.test_watcher_sweep_match(None, "") is False


# ---------------------------------------------------------------------------
# 2. Equivalence: workspace key derivation
# ---------------------------------------------------------------------------

# (path, expected key) - generated by running Get-WatchersWorkspaceKey in the
# live .ps1. The first two also appear in the mcpw-ybs close reason, which is an
# independent corroboration that these are the real production keys.
WORKSPACE_KEY_VECTORS = [
    ("J:\\audio\\MCP-Watchers", "ad90e3fb"),
    ("J:\\audio\\VAD", "77442b14"),
    ("C:\\Temp\\vad-watchers\\77442b14", "6e9a88f7"),
    # trailing separator is trimmed before hashing
    ("J:\\audio\\MCP-Watchers\\", "ad90e3fb"),
    # normalisation is case-insensitive
    ("J:\\AUDIO\\mcp-watchers", "ad90e3fb"),
    ("J:\\audio\\MCP-Watchers\\Modules", "68ebdd8a"),
    ("/tmp/x", "2e56aa36"),
]


def test_workspace_key_matches_ps1_vectors():
    for path, expected in WORKSPACE_KEY_VECTORS:
        actual = watcher_workspace.get_watchers_workspace_key(path)
        assert actual == expected, (
            f"get_watchers_workspace_key({path!r}) returned {actual!r}, "
            f".ps1 returned {expected!r}"
        )


def test_workspace_key_is_eight_lowercase_hex():
    key = watcher_workspace.get_watchers_workspace_key("J:\\audio\\MCP-Watchers")
    assert len(key) == 8
    assert re.fullmatch(r"[0-9a-f]{8}", key), key


# ---------------------------------------------------------------------------
# 2. Equivalence: process attribution
# ---------------------------------------------------------------------------

KEY_THIS = "77442b14"
ROOT_THIS = "J:\\audio\\MCP-Watchers"

# (command_line, key, root, expected) - generated by running
# Test-WatchersProcessAttribution in the live .ps1.
ATTRIBUTION_VECTORS = [
    ("ps -File C:\\Temp\\vad-watchers\\77442b14\\panes\\tail_grepai.ps1", KEY_THIS, ROOT_THIS, True),
    ("cmd --repo j:\\AUDIO\\vad", KEY_THIS, ROOT_THIS, False),
    ("cmd -c C:\\anything", KEY_THIS, ROOT_THIS, False),
    ("", KEY_THIS, ROOT_THIS, False),
    ("cmd", "", "", False),
    # ordinal-ignore-case on the root marker
    ("cmd -File J:\\AUDIO\\MCP-WATCHERS\\x", KEY_THIS, ROOT_THIS, True),
    # the 4-character floor on the root marker: both sides of the boundary, with
    # a root that IS contained in the command line, so only length decides.
    ("cmd -c C:\\ab", "", "C:\\", False),
    ("cmd -c C:\\ab", "", "C:\\a", True),
]


def test_attribution_matches_ps1_vectors():
    for command_line, key, root, expected in ATTRIBUTION_VECTORS:
        actual = watcher_workspace.test_watchers_process_attribution(command_line, key, root)
        assert actual is expected, (
            f"test_watchers_process_attribution({command_line!r}, {key!r}, {root!r}) "
            f"returned {actual}, .ps1 returned {expected}"
        )


def test_attribution_fails_safe_on_unattributable_process():
    """No marker means never terminate: skipping an orphan is harmless, killing a
    sibling repository's watcher is not."""
    assert watcher_workspace.test_watchers_process_attribution("cmd /c whatever", "", "") is False
    assert watcher_workspace.test_watchers_process_attribution(None, KEY_THIS, ROOT_THIS) is False


def test_short_workspace_root_is_ignored():
    """A drive root such as C:\\ would attribute every process on the machine.

    Vectors generated by running the .ps1 with the SAME command line and two
    roots one character apart, so length is the only variable: len('C:\\') == 3
    is refused, len('C:\\a') == 4 is accepted.
    """
    assert watcher_workspace.test_watchers_process_attribution("cmd -c C:\\ab", "", "C:\\") is False
    assert watcher_workspace.test_watchers_process_attribution("cmd -c C:\\ab", "", "C:\\a") is True
    # ...and a long-enough root that simply is not in the command line still fails
    assert watcher_workspace.test_watchers_process_attribution("cmd -c C:\\ab", "", "C:\\zz") is False


# ---------------------------------------------------------------------------
# Workspace root resolution (no .ps1 vector: it depends on the live location)
# ---------------------------------------------------------------------------


def test_workspace_root_prefers_explicit_path_then_env_then_cwd():
    assert watcher_workspace.get_watchers_workspace_root(
        path="J:\\a\\", env={"VAD_WATCHERS_WORKSPACE_ROOT": "J:\\b"}, cwd="J:\\c"
    ) == "J:\\a"
    assert watcher_workspace.get_watchers_workspace_root(
        env={"VAD_WATCHERS_WORKSPACE_ROOT": "J:\\b\\"}, cwd="J:\\c"
    ) == "J:\\b"
    assert watcher_workspace.get_watchers_workspace_root(env={}, cwd="J:\\c\\") == "J:\\c"


def test_workspace_root_never_returns_the_script_folder_by_accident():
    """$scriptDir is a separate concept; it must only appear when explicitly asked
    for or when it really is the current location."""
    assert watcher_workspace.get_watchers_workspace_root(env={}, cwd="J:\\audio\\MCP-Watchers") == (
        "J:\\audio\\MCP-Watchers"
    )


# ---------------------------------------------------------------------------
# 1. Behaviour: the incremental log tail
# ---------------------------------------------------------------------------


def _tail(path, offset, backlog=65536):
    return watcher_log_tail.read_watcher_log_tail(str(path), offset, backlog)


def test_missing_file_leaves_the_offset_untouched(tmp_path):
    result = _tail(tmp_path / "nope.log", 42)
    assert result.lines == ()
    assert result.offset == 42
    assert result.rotated is False


def test_reads_only_the_appended_bytes(tmp_path):
    log = tmp_path / "w.log"
    log.write_bytes(b"alpha\nbeta\ngamma")
    first = _tail(log, 0)
    assert first.lines == ("alpha", "beta", "gamma")
    assert first.offset == len(b"alpha\nbeta\ngamma")
    assert first.rotated is False

    # Nothing new: same offset, no lines, no rotation.
    second = _tail(log, first.offset)
    assert second.lines == ()
    assert second.offset == first.offset
    assert second.rotated is False


def test_unterminated_final_line_is_displayed(tmp_path):
    """repowise writes its final "N changed file(s)" line with NO trailing CR/LF.
    Suppressing unterminated lines would hide that change-event line forever."""
    log = tmp_path / "w.log"
    log.write_bytes(b"header\n3 changed file(s)")
    result = _tail(log, 0)
    assert result.lines == ("header", "3 changed file(s)")


def test_leading_newline_of_a_delta_yields_an_empty_line(tmp_path):
    """Faithful quirk of the original, not a new bug: the newline that terminated
    the PREVIOUS read is part of the next delta, so it splits to a leading ''."""
    log = tmp_path / "w.log"
    log.write_bytes(b"a\nb")
    first = _tail(log, 0)
    assert first.lines == ("a", "b")

    with open(log, "ab") as fh:
        fh.write(b"\nc\n")
    second = _tail(log, first.offset)
    assert second.lines == ("", "c")


def test_crlf_is_split(tmp_path):
    log = tmp_path / "w.log"
    log.write_bytes(b"a\r\nb\r\n")
    assert _tail(log, 0).lines == ("a", "b")


def test_utf8_bom_is_skipped_only_at_offset_zero(tmp_path):
    log = tmp_path / "w.log"
    log.write_bytes(b"\xef\xbb\xbfx\ny")
    assert _tail(log, 0).lines == ("x", "y")


def test_truncation_reports_rotation_and_reseats(tmp_path):
    log = tmp_path / "w.log"
    log.write_bytes(b"z" * 100)
    assert _tail(log, 100).offset == 100

    log.write_bytes(b"fresh\n")  # truncated to 6 bytes
    result = _tail(log, 100)
    assert result.rotated is True
    assert result.offset == len(b"fresh\n")
    assert result.lines == ("fresh",)


def test_reseat_keeps_a_bounded_backlog(tmp_path):
    log = tmp_path / "w.log"
    log.write_bytes(b"x" * 1000)
    log.write_bytes(b"y" * 100)  # shrink, then ask for a 50-byte backlog
    result = _tail(log, 1000, backlog=50)
    assert result.rotated is True
    assert result.offset == 100
    assert result.lines == ("y" * 50,)


def test_malformed_bytes_are_replaced_not_raised(tmp_path):
    """A torn multi-byte write must not crash the tailer. The .ps1 decoder
    replaces malformed sequences with U+FFFD; so does this one."""
    log = tmp_path / "w.log"
    log.write_bytes(b"ok\n\xff\xfe bad\n")
    result = _tail(log, 0)
    assert result.lines[0] == "ok"
    assert "\ufffd" in result.lines[1]


# ---------------------------------------------------------------------------
# The originals must remain, and remain live
# ---------------------------------------------------------------------------


def test_powershell_originals_are_still_present():
    """The port is additive until the launcher switches over. Deleting an
    original before its consumer is ported would break the running stack."""
    for original in (PATTERNS_PS1, WORKSPACE_PS1, LOG_TAIL_PS1):
        assert original.is_file(), f"{original.name} disappeared from Modules\\"
